module.exports = Object.freeze({

    PARAM_SESSION_ID: 'sid',
    PARAM_UUID: 'uuid',

    CMD_CODE_REPORT_SCREEN_INFO: "REPORT_SCREEN_INFO",
    CMD_CODE_UPDATE_SCREEN_INFO: "UPDATE_SCREEN_INFO"

});
